### PR TITLE
22 nr7 application UI formatted well

### PR DESCRIPTION
**Pull request by Hasan-Ahmad8**

### CODE REVIEW

**Review by w1-ll — CHANGES_REQUESTED** [review]
Delete the head at lines 1-3, delete line 41 and 42 fo rhte = symbols.  Delete the head and arrow in line 84-86.  Delete 94-96.  In line 23 at the UHome.html, Delete the font-awesome cloudfare thingy

**Review by w1-ll — CHANGES_REQUESTED** [review]
Delete line 38, 79, 87, and 88

**Review by w1-ll — APPROVED** [review]
Looks much better

**Review by kratkiewiczk — APPROVED** [review]
After changes looks good

**Pull request merged**
